name: Build & Test

on:
  push:
    branches: [ wizards ]
  pull_request:
    branches: [ wizards ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet-version: ['7.0.x', '8.0.x', '10.0.x']

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Test ${{ matrix.dotnet-version }}
      run: dotnet test --configuration Release --framework ${{ matrix.dotnet-version }} -v n
